version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-8.0
    restart: always                       
    environment:
      MYSQL_DATABASE: 'cadastro_produtos'              
      MYSQL_USER: 'uva'                
      MYSQL_PASSWORD: 'alunouva'          
      MYSQL_ROOT_PASSWORD: 'alunouva'     
    ports:
      - '3306:3306'                       
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
        mysql-db: